site_name: Xu Group Wiki
site_url: https://sitename.example
theme:
  name: material

  #.2
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  #.3
  icon:
    logo: fontawesome/brands/wikipedia-w
  
  features:
    - navigation.footer
  #.1
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  #emoji, coin
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  #admonition
  - admonition
  - pymdownx.details
  #content
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  #diagram
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  
# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2024 James Willett